# Build settings

source: .
destination: ./_site
markdown: kramdown
# don't change the following; coderay will break the embedded
# annotations.
kramdown:
  enable_coderay: false
permalinks: pretty
safe: true
markdown_ext: md

##############################################################################

# Site settings

name: Lifestyle Entities Annotation Docs
homeurl: "https://esmaeilnourani.github.io/lifestylefactors-entities-annotation-docs/"
editurl: "https://github.com/esmaeilnourani/lifestylefactors-entities-annotation-docs/edit/gh-pages"
issueurl: "https://github.com/esmaeilnourani/lifestylefactors-entities-annotation-docs/issues"

##############################################################################

# Collection settings

collections:
  entity:
    output: true
